services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_ID=node1
      - NODE_HOST=node1
      - NODE_PORT=8080
      - CLUSTER_NODES=node1:8080,node2:8080,node3:8080
    ports:
      - "8081:8080"

  node2:
    build: .
    container_name: node2
    environment:
      - NODE_ID=node2
      - NODE_HOST=node2
      - NODE_PORT=8080
      - CLUSTER_NODES=node1:8080,node2:8080,node3:8080
    ports:
      - "8082:8080"

  node3:
    build: .
    container_name: node3
    environment:
      - NODE_ID=node3
      - NODE_HOST=node3
      - NODE_PORT=8080
      - CLUSTER_NODES=node1:8080,node2:8080,node3:8080
    ports:
      - "8083:8080"
